import Head from 'next/head'
import Banner from '../components/banner/Banner'
import Footer from '../components/feed/Footer'
import LargeCard from '../components/feed/LargeCard'
import MidCard from '../components/feed/MidCard'
import SmallCard from '../components/feed/SmallCard'
import Header from '../components/header/Header'

export default function Home ({ exploreData, cardsData }) {
  return (
    <div className='overflow-y-scroll scrollbar-hide'>
      <Head>
        <title>Home-finder</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <Banner />
      <main className='mx-auto max-w-7xl px-8 sm:px-16 overflow-y-scroll scrollbar-hide'>
        {/**Small cards */}
        <section className='pt-6'>
          <h2
            className='
           text-4xl
           font-semibold
           pb-5
           '
          >
            Explore nearby
          </h2>
          <div
            className='
          grid 
          grid-cols-1
          sm:grid-cols-2
          lg:grid-cols-3
          xl:grid-cols-4
          '
          >
            {/**Pull data from API */}
            {exploreData.map(({ img, distance, location }) => (
              <SmallCard
                key={img}
                img={img}
                location={location}
                distance={distance}
              />
            ))}
          </div>
        </section>
        {/**Mid cards */}
        <section className=''>
          <h2
            className='
                text-4xl
                font-semibold
                py-8
                '
          >
            Live Anywhere
          </h2>
          <div
            className='
          flex
          items-center
          overflow-x-scroll
          space-x-3
          scrollbar-hide
          '
          >
            {cardsData?.map(({ img, title }) => (
              <MidCard key={img} img={img} title={title} />
            ))}
          </div>
        </section>
        <LargeCard
          img='https://links.papareact.com/4cj'
          title='The Greatest Outdoors'
          description='Wishlists curated by Airbnb'
          buttonText='Get Inspired'
        />
      </main>
      <Footer />
    </div>
  )
}

export async function getStaticProps (context) {
  const exploreData = await fetch('https://links.papareact.com/pyp').then(res =>
    res.json()
  )

  const cardsData = await fetch('https://links.papareact.com/zp1').then(res =>
    res.json()
  )

  return {
    props: {
      exploreData,
      cardsData
    }
  }
}
